# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
before_script:
    - bash php-tools/docker-entrypoint.sh > /dev/null
testgophp81:
    image: sailenicolas/gophp:8.1.3
    only:
        - php8
#    cache:
#        key: "$CI_COMMIT_REF_SLUG"
#        paths:
#            - vendor/
    script:
        - make test
#testgophp80:
#    image: sailenicolas/gophp:8.0.17
#    only:
#        - php8
#    cache:
#        key: "$CI_COMMIT_REF_SLUG"
#        paths:
#            - vendor/
#    script:
#        - make test


