name: Setup
runs:
    using: composite
    steps:
        - shell: bash
          run: |
              set -x
              chmod +x ./.github/scripts/install.sh
              ./.github/scripts/install.sh
